# Generated by Django 4.2.7 on 2025-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lattitude', models.FloatField()),
                ('lon', models.FloatField()),
                ('temp_c', models.FloatField()),
                ('temp_color', models.CharField(max_length=7)),
                ('wind_kph', models.FloatField()),
                ('wind_color', models.CharField(max_length=7)),
                ('cloud', models.IntegerField()),
                ('cloud_color', models.CharField(max_length=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
